#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $block_button = $ENV{BLOCK_BUTTON} || 0;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# show info on right click
if ($block_button eq '1') {
        system('st -n floating -e "/home/christian/.i3/i3blocks-scripts/battery_script"');
}

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent";

$short_text = $full_text;

# Consider color and urgent flag only on discharge
if ($status eq 'Discharging') {
    if ($percent < 6) {
            print '<span foreground="#8787AF">  </span>';
            print "$full_text\n";
            print "$short_text\n";
            exit(33);
    } elsif ($percent < 25) {
            print '<span foreground="#8787AF">  </span>';
            print "$full_text\n";
            print "$short_text\n";
            print "#666666\n";
    } elsif ($percent < 50) {
            print '<span foreground="#8787AF">  </span>';
            print "$full_text\n";
            print "$short_text\n";
            print "#888888\n";
    } elsif ($percent < 75) {
            print '<span foreground="#8787AF">  </span>';
            print "$full_text\n";
            print "$short_text\n";
            print "#AAAAAA\n";
    } else {
            print '<span foreground="#8787AF">  </span>';
            print "$full_text\n";
            print "$short_text\n";
            print "#CCCCCC\n";
    }
}
else {
    print '<span foreground="#8787AF">  </span>';
    print "$full_text\n";
    print "$short_text\n";
}

exit(0);
