#!/bin/bash

# Block buttons
case $BLOCK_BUTTON in
    1) sudo xbacklight -set 30 -time 0 -steps 1;;
    2) sudo xbacklight -set 50 -time 0 -steps 1;;
    3) sudo xbacklight -set 70 -time 0 -steps 1;;
    4) sudo xbacklight -inc 5 -time 0 -steps 1;;
    5) sudo xbacklight -dec 5 -time 0 -steps 1;;
esac

# Get brightness
brightness=$(xbacklight -get)

printf "<span foreground='#FAC863'>  </span>%s\n" "$brightness"
