#!/bin/bash

show_cover() {
    notify-send -i cover "$2" "$1"
}

get_cover() {
    album="$1"
    artist="$2"
    covername="$3"
    glyrc cover --artist "$artist" --album "$album" -w "$covername" 2>/dev/null 1>&2
    mogrify -thumbnail 128x128 "$covername"
}

check_cover() {
    album=$(mpc -f "%album%" current)
    artist=$(mpc -f "%artist%" current)
    song=$(mpc -f "%title%" current)
    covername=~/Musik/${artist}_${album}.png
    if [[ ! -f "$covername" ]]; then
        get_cover "$album" "$artist" "$covername"
    fi
    notify-send -i "${artist}_${album}" "$artist - $album" "$song"
}

check_cover
