#!/bin/bash

get_window_names() {
    for win in $(xdotool search --onlyvisible --name ""); do
        xdotool getwindowname $win | cut -d " " -f1
    done
}

windows=$(get_window_names | grep -v "i3" | tr "\n" " ")
printf "%s\n" "$windows"
