#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"

case $BLOCK_BUTTON in
    3) urxvt -name floating -e htop ;;
esac

printf '<span foreground="#8DB5DD">RAM </span>'

awk 'NR==1 {total=$2;} NR==3 {free=$2;} END {printf "%0.f\n", (1-free/total)*100;}' /proc/meminfo
