#!/bin/sh

uname -sr
printf '\n'
cat ~/.i3/info/update_info
perl -E 'say "─" x 80'
if [[ $(cat ~/.i3/info/update_names) ]]; then
    cat ~/.i3/info/update_names
    printf "\n"
    read -n1 -p "Update? [Y/n]  " update

    if [[ $update != n ]] && [[ $update != N ]]; then
        pacaur -Syu
    fi
else
    read -n1 input
fi
