#!/bin/bash

# Block buttons
case $BLOCK_BUTTON in
    1 ) ~/.i3/volnoti-set.sh 1>/dev/null 2>&1;;
    4 ) ~/.i3/volnoti-set.sh + 1>/dev/null 2>&1;;
    5 ) ~/.i3/volnoti-set.sh - 1>/dev/null 2>&1;;
esac

# Get volume
vol=$(amixer -c 0 get Master | grep Mono | cut -d " " -f6 | tr -d '[]' | tr -d '\n' | tr -d '%')
mute=$(amixer -c 0 get Master | grep Mono | cut -d " " -f8)

# Display properly
if [ $mute == "[on]" ]; then
    printf "<span foreground='#FAC863'> </span> %s" "$vol"
else
    printf "<span foreground='#FAC863'>  </span>"
    printf "%s\n\n#888888\n"  "$vol"
fi
