#!/bin/bash

# Get location code
loc=$(bash < ~/.i3/info/getlocation.sh)

# Open website with weather information on click
case $BLOCK_BUTTON in
    1) $BROWSER http://www.wetter.com/suche/?q="$loc" ;;
esac

# Get information
data=$(curl -s --connect-timeout 30 wttr.in/"$loc" | sed -n "3,4p")
weather=$(printf "%s\n" "$data" | awk 'NR == 1 {print $NF}')
temperature=$(printf "%s\n" "$data" | \
    awk 'NR == 2 {print $(NF - 1)}' | \
    sed -e "s/\x1b\[.\{1,9\}m//g")

# Meteocons font for the nice icons
printf '<span font="meteocons">'
if [[ $weather == *"Sun"* ]]; then
    printf '<span foreground="#F3FF0D"></span>'
elif [[ $weather == *"Rain"* || $weather == *"Shower"* ]]; then
    printf '<span foreground="#6B93BB"></span>'
elif [[ $weather == *"Cloud"* ]]; then
    printf '<span foreground="#888888"></span>'
elif [[ $weather == *"Mist"* || $weather == *"Fog"* || $weather == *"Haze"* ]]; then
    printf '<span foreground="#FFFFFF"></span>'
elif [[ $weather == *"Clear"* ]]; then
    printf '<span foreground="#888888"></span>'
elif [[ $weather == *"Snow"* || $weather == *"Flurr"* ]]; then
    printf '<span foreground="#FFFFFF"></span>'
else
    printf "%s  " "$weather"
fi
printf '</span>  '
printf "%sC\n" "$temperature"

# Blue for cold, yellow for warm temperature
if [[ $temperature -lt 0 ]]; then
    printf "\n#AFD7FF\n"
elif [[ $temperature -gt 20 ]]; then
    printf "\n#F3FF0D\n"
fi
