#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

# Open wifi-menu on right-click
case $BLOCK_BUTTON in
    1) urxvt -name floating -e sudo wifi-menu ;;
esac

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

# Label
printf '<span foreground="#8787AF">  </span>'

# If there is signal, display the quality, otherwise --- and urgent
if [[ -n $QUALITY ]]; then
    echo $QUALITY # full text
    echo $QUALITY # short text
else
    echo "---"
    echo "---"
    exit 33
fi

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#CCCCCC"
elif [[ $QUALITY -ge 60 ]]; then
    echo "#AAAAAA"
elif [[ $QUALITY -ge 40 ]]; then
    echo "#888888"
elif [[ $QUALITY -lt 40 ]]; then
    echo "#666666"
fi
