#!/usr/bin/env python3

import datetime
import os
import requests
import sys


def fail():
    """Print default icon and exit."""
    print(" ---")
    sys.exit(1)


def read_info_file():
    """Read zip and openweather api key from file.

    The file must be located in ~/.local/share/openweather_info and have the
    zip code in the first line and the api key in the second line.

    Returns:
        zip code, api key
    """
    with open(os.path.expanduser("~/.local/share/openweather_info")) as f:
        lines = f.readlines()
    return lines[0].rstrip(), lines[1].rstrip()


ZIP, API_KEY = read_info_file()
UNITS = "Metric"
UNIT_KEY = "C"


try:
    REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?zip={}&appid={}&units={}".format(ZIP, API_KEY, UNITS))
except requests.exceptions.ConnectionError:
    fail()
try:
    # HTTP CODE = OK
    if REQ.status_code == 200:
        CURRENT = REQ.json()["weather"][0]["description"].capitalize()
        ID = int(float(REQ.json()["weather"][0]["id"]))
        TEMP = int(float(REQ.json()["main"]["temp"]))
        HOUR = datetime.datetime.now().hour
    else:
        fail()
except (ValueError, IOError):
    fail()

if ID >= 200 and ID <= 232:
    ICON = ""
elif ID >= 310 and ID <= 531:
    ICON = ""
elif ID >= 600 and ID <= 622:
    ICON = ""
elif ID >= 701 and ID <= 761:
    ICON = ""
elif ID >= 801 and ID <= 804:
    if HOUR >= 6 and HOUR <= 19:
        ICON = ""
    else:
        ICON = ""
elif ID >= 900 and ID <= 902 or ID >= 957 and ID <= 962:
	ICON = ""
elif ID == 903 or ID == 906:
	ICON = ""
elif ID == 904:
	ICON = ""
elif ID == 905 or ID >= 951 and ID <= 956:
	ICON = ""
else:
    if HOUR >= 6 and HOUR <= 19:
        ICON = ""
    else:
        ICON = ""

print(" %%{F#ECEFF4}%s%%{F-} %i°%s" % (ICON, TEMP, UNIT_KEY)) # Icon without description
